//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JapaneseTeacher.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JapaneseTeacher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на [{&quot;Level&quot;:&quot;1&quot;,&quot;Text&quot;:&quot;あ&quot;,&quot;Translation&quot;:&quot;a&quot;,&quot;Encounters&quot;:0,&quot;Mistakes&quot;:0,&quot;StreakForMistakes&quot;:0,&quot;Streak&quot;:0,&quot;TimesNotSeen&quot;:0},{&quot;Level&quot;:&quot;1&quot;,&quot;Text&quot;:&quot;か&quot;,&quot;Translation&quot;:&quot;ka&quot;,&quot;Encounters&quot;:0,&quot;Mistakes&quot;:0,&quot;StreakForMistakes&quot;:0,&quot;Streak&quot;:0,&quot;TimesNotSeen&quot;:0},{&quot;Level&quot;:&quot;1&quot;,&quot;Text&quot;:&quot;し&quot;,&quot;Translation&quot;:&quot;shi&quot;,&quot;Encounters&quot;:0,&quot;Mistakes&quot;:0,&quot;StreakForMistakes&quot;:0,&quot;Streak&quot;:0,&quot;TimesNotSeen&quot;:0},{&quot;Level&quot;:&quot;1&quot;,&quot;Text&quot;:&quot;つ&quot;,&quot;Translation&quot;:&quot;tsu&quot;,&quot;Encounters&quot;:0,&quot;Mistakes&quot;:0,&quot;StreakForMistakes&quot;:0,&quot;Streak&quot;:0,&quot;TimesNotSeen&quot;:0},{&quot;Level&quot;:&quot;1&quot;,&quot;Text&quot;:&quot;ね [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Hiragana {
            get {
                return ResourceManager.GetString("Hiragana", resourceCulture);
            }
        }
    }
}
